#
# TTP: Tiny TLS Proxy: a very simple TLS proxy server with
#                      focus on resource consumption.
#
# Made by Davidson Francis.
# This is free and unencumbered software released into the public domain.
#

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    name: Build for ARMv6 (compatible with v7 and Aarch64), and push to Dockerhub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Download & extract GCC v11.2/musl (b76f37f) for armv6
      run:  toolchain/toolchain.sh "download_musl_armv6"
    - name: Build TTP for armv6
      run:  toolchain/toolchain.sh "build_ttp_armv6"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image for armv6/v7 and aarch64
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        platforms: linux/arm/v6, linux/arm/v7, linux/arm64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ttp:latest
